<a href="https://colab.research.google.com/github/Jacofeldman/Metodos1_JacoboFeldman/blob/main/tarea4/Punto13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import matplotlib.pyplot as plt
def jacobiano_central_orden4(func, x, h):

    n = len(x)
    m = len(func(x))
    J = np.zeros((m, n))

    for i in range(n):
        x_i_plus_h = np.array(x)
        x_i_minus_h = np.array(x)
        x_i_plus_2h = np.array(x)
        x_i_minus_2h = np.array(x)

        x_i_plus_h[i] += h
        x_i_minus_h[i] -= h
        x_i_plus_2h[i] += 2 * h
        x_i_minus_2h[i] -= 2 * h

        J[:, i] = (func(x_i_plus_2h) - 8 * func(x_i_plus_h) +
                   8 * func(x_i_minus_h) - func(x_i_minus_2h)) / (12 * h)

    return J
def funcion_568(x):

    x1, x2, x3 = x
    f1 = 6 * x1 - 2 * np.cos(x2 * x3) - 1
    f2 = 9 * x2 + np.sqrt(x1**2 + np.sin(x3) + 1.06) + 0.9
    f3 = 60 * x3 + 3 * np.exp(-x1 * x2) + 10 * np.pi - 3
    return np.array([f1, f2, f3])


x0 = np.array([0.5, 0.5, 0.5])
h = 0.01


jacobiano_orden4 = jacobiano_central_orden4(funcion_568, x0, h)
print("Jacobiano (orden O(h^4)) en x = (0.5, 0.5, 0.5):")
print(jacobiano_orden4)
def jacobiano_central_orden2(func, x, h):

    n = len(x)
    m = len(func(x))
    J = np.zeros((m, n))

    for i in range(n):
        x_i_plus_h = np.array(x)
        x_i_minus_h = np.array(x)

        x_i_plus_h[i] += h
        x_i_minus_h[i] -= h

        J[:, i] = (func(x_i_plus_h) - func(x_i_minus_h)) / (2 * h)

    return J

# Estimar el Jacobiano usando el operador de orden O(h^2)
jacobiano_orden2 = jacobiano_central_orden2(funcion_568, x0, h)
print("\nJacobiano (orden O(h^2)) en x = (0.5, 0.5, 0.5):")
print(jacobiano_orden2)


Jacobiano (orden O(h^4)) en x = (0.5, 0.5, 0.5):
[[ -6.          -0.24740396  -0.24740396]
 [ -0.37377753  -9.          -0.32802064]
 [  1.16820117   1.16820117 -60.        ]]

Jacobiano (orden O(h^2)) en x = (0.5, 0.5, 0.5):
[[ 6.          0.24740293  0.24740293]
 [ 0.37376854  9.          0.32801836]
 [-1.16820604 -1.16820604 60.        ]]


In [35]:
# Comparar precisión para diferentes valores de h
h_values = [0.1, 0.05, 0.01, 0.005,0.001,0.0001]
for h in h_values:
    jacobiano_orden4 = jacobiano_central_orden4(funcion_568, x0, h)
    jacobiano_orden2 = jacobiano_central_orden2(funcion_568, x0, h)
    x=np.linalg.norm(jacobiano_orden4)
    y=np.linalg.norm(jacobiano_orden2)

    error = x-y
    print(f"Error entre Jacobiano de orden O(h^4) y O(h^2) para h={h}: {error:}")


Error entre Jacobiano de orden O(h^4) y O(h^2) para h=0.1: -1.1172222599498127e-05
Error entre Jacobiano de orden O(h^4) y O(h^2) para h=0.05: -2.7748508415470496e-06
Error entre Jacobiano de orden O(h^4) y O(h^2) para h=0.01: -1.107592026983184e-07
Error entre Jacobiano de orden O(h^4) y O(h^2) para h=0.005: -2.768752693782517e-08
Error entre Jacobiano de orden O(h^4) y O(h^2) para h=0.001: -1.1086100926149811e-09
Error entre Jacobiano de orden O(h^4) y O(h^2) para h=0.0001: -1.7422507880837657e-11
