<a href="https://colab.research.google.com/github/Jacofeldman/Metodos1_JacoboFeldman/blob/main/tarea4/Punto10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

def calcular_theta(A, MI, MJ):
    """Calcula el ángulo theta para la rotación."""
    if A[MI, MI] == A[MJ, MJ]:
        return np.pi / 4  # 45 grados
    return 0.5 * np.arctan(2 * A[MI, MJ] / (A[MI, MI] - A[MJ, MJ]))

def crear_matriz_rotacion(theta, MI, MJ, n):
    """Crea la matriz de rotación R para los índices MI y MJ."""
    R = np.eye(n)
    R[MI, MI] = np.cos(theta)
    R[MJ, MJ] = np.cos(theta)
    R[MI, MJ] = -np.sin(theta)
    R[MJ, MI] = np.sin(theta)
    return R

def metodo_jacobi_modificado(A, itmax=100, tolerancia=1e-10):
    """Implementa el método de Jacobi para diagonalizar matrices simétricas."""
    n = A.shape[0]
    V = np.eye(n)

    for it in range(itmax):
        # Buscar el elemento fuera de la diagonal más grande
        mayor, MI, MJ = 0, 0, 0
        for i in range(n):
            for j in range(i + 1, n):
                if abs(A[i, j]) > abs(mayor):
                    mayor, MI, MJ = A[i, j], i, j

        # Verificar convergencia
        if abs(mayor) < tolerancia:
            break

        # Calcular el ángulo de rotación
        theta = calcular_theta(A, MI, MJ)
        R = crear_matriz_rotacion(theta, MI, MJ, n)

        # Actualizar la matriz A y los vectores propios V
        A = R.T @ A @ R
        V = V @ R

    # Extraer los valores propios de la diagonal de A
    valores = np.diag(A)
    vectores = V

    return valores, vectores, it

# Matriz de ejemplo
A = np.array([[4, 1, 1],
              [1, 3, 2],
              [1, 2, 5]])

# Ejecutar el método de Jacobi
valores_jacobi, vectores_jacobi, iteraciones = metodo_jacobi_modificado(A)

# Mostrar los resultados del método de Jacobi
print("Valores propios (método de Jacobi):", valores_jacobi)
print("Vectores propios (método de Jacobi):\n", vectores_jacobi)
print("Número de iteraciones:", iteraciones)

# Comparar con los resultados de numpy
valores_numpy, vectores_numpy = np.linalg.eig(A)

# Mostrar los resultados de NumPy
print("\nValores propios (NumPy):", valores_numpy)
print("Vectores propios (NumPy):\n", vectores_numpy)


Valores propios (método de Jacobi): [3.39729507 1.70759841 6.89510652]
Vectores propios (método de Jacobi):
 [[ 0.88573564 -0.17059871  0.43170413]
 [-0.07589338  0.86427949  0.49725362]
 [-0.45794385 -0.47319874  0.75257583]]
Número de iteraciones: 8

Valores propios (NumPy): [6.89510652 3.39729507 1.70759841]
Vectores propios (NumPy):
 [[ 0.43170413  0.88573564  0.17059871]
 [ 0.49725362 -0.07589338 -0.86427949]
 [ 0.75257583 -0.45794385  0.47319874]]
