<a href="https://colab.research.google.com/github/Jacofeldman/Metodos1_JacoboFeldman/blob/main/tarea4/Punto10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def calcular_theta(A, MI, MJ):

    if A[MI, MI] == A[MJ, MJ]:
        return np.pi / 4
    return 0.5 * np.arctan(2 * A[MI, MJ] / (A[MI, MI] - A[MJ, MJ]))

def crear_matriz_rotacion(theta, MI, MJ, n):

    R = np.eye(n)
    R[MI, MI] = np.cos(theta)
    R[MJ, MJ] = np.cos(theta)
    R[MI, MJ] = -np.sin(theta)
    R[MJ, MI] = np.sin(theta)
    return R

def metodo_jacobi_modificado(A, itmax=100, tolerancia=1e-10):

    n = A.shape[0]
    V = np.eye(n)

    for it in range(itmax):

        mayor, MI, MJ = 0, 0, 0
        for i in range(n):
            for j in range(i + 1, n):
                if abs(A[i, j]) > abs(mayor):
                    mayor, MI, MJ = A[i, j], i, j


        if abs(mayor) < tolerancia:
            break


        theta = calcular_theta(A, MI, MJ)
        R = crear_matriz_rotacion(theta, MI, MJ, n)


        A = R.T @ A @ R
        V = V @ R


    valores = np.diag(A)
    vectores = V

    return valores, vectores, it


A = np.array([[4, 1, 1],
              [1, 3, 2],
              [1, 2, 5]])


valores_jacobi, vectores_jacobi, iteraciones = metodo_jacobi_modificado(A)


print("Valores propios (método de Jacobi):", valores_jacobi)
print("Vectores propios (método de Jacobi):\n", vectores_jacobi)
print("Número de iteraciones:", iteraciones)


valores_numpy, vectores_numpy = np.linalg.eig(A)


print("\nValores propios (NumPy):", valores_numpy)
print("Vectores propios (NumPy):\n", vectores_numpy)


Valores propios (método de Jacobi): [3.39729507 1.70759841 6.89510652]
Vectores propios (método de Jacobi):
 [[ 0.88573564 -0.17059871  0.43170413]
 [-0.07589338  0.86427949  0.49725362]
 [-0.45794385 -0.47319874  0.75257583]]
Número de iteraciones: 8

Valores propios (NumPy): [6.89510652 3.39729507 1.70759841]
Vectores propios (NumPy):
 [[ 0.43170413  0.88573564  0.17059871]
 [ 0.49725362 -0.07589338 -0.86427949]
 [ 0.75257583 -0.45794385  0.47319874]]
