<a href="https://colab.research.google.com/github/Jacofeldman/Metodos1_JacoboFeldman/blob/main/tarea4/Punto8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def descomposicion_LU(A):

    n = len(A)


    L = np.zeros((n, n))
    U = np.zeros((n, n))


    for i in range(n):

        for k in range(i, n):
            suma_U = sum(L[i][j] * U[j][k] for j in range(i))
            U[i][k] = A[i][k] - suma_U


        for k in range(i, n):
            if i == k:
                L[i][i] = 1
            else:
                suma_L = sum(L[k][j] * U[j][i] for j in range(i))
                L[k][i] = (A[k][i] - suma_L) / U[i][i]

    return L, U

A = np.array([[4, -2, 1],
              [20, -7, 12],
              [-8, 13, 17]])


L, U = descomposicion_LU(A)


print("Matriz L:")
print(L)
print("\nMatriz U:")
print(U)


Matriz L:
[[ 1.  0.  0.]
 [ 5.  1.  0.]
 [-2.  3.  1.]]

Matriz U:
[[ 4. -2.  1.]
 [ 0.  3.  7.]
 [ 0.  0. -2.]]
