<a href="https://colab.research.google.com/github/Jacofeldman/Metodos1_JacoboFeldman/blob/main/tarea4/Punto13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

def jacobiano_central_orden4(func, x, h):
    """
    Estima el Jacobiano de una función vectorial usando el operador de derivada central de orden O(h^4).

    :param func: Función vectorial que toma un vector x y devuelve un vector.
    :param x: Punto en el que se calcula el Jacobiano (vector).
    :param h: Tamaño del paso.
    :return: Matriz Jacobiana estimada.
    """
    n = len(x)  # Dimensión del vector
    m = len(func(x))  # Dimensión del vector de salida
    J = np.zeros((m, n))

    for i in range(n):
        x_i_plus_h = np.array(x)
        x_i_minus_h = np.array(x)
        x_i_plus_2h = np.array(x)
        x_i_minus_2h = np.array(x)

        x_i_plus_h[i] += h
        x_i_minus_h[i] -= h
        x_i_plus_2h[i] += 2 * h
        x_i_minus_2h[i] -= 2 * h

        J[:, i] = (func(x_i_plus_2h) - 8 * func(x_i_plus_h) +
                   8 * func(x_i_minus_h) - func(x_i_minus_2h)) / (12 * h)

    return J
def funciones_5_68(x):
    """Evalúa las ecuaciones del sistema (5.68)."""
    x1, x2, x3 = x
    f1 = 6 * x1 - 2 * np.cos(x2 * x3) - 1
    f2 = 9 * x2 - np.sqrt(x1**2 + np.sin(x3) + 1.06) + 0.9
    f3 = 60 * x3 + 3 * np.exp(-x1 * x2) + 10 * np.pi - 3
    return np.array([f1, f2, f3])

# Punto en el que se estima el Jacobiano
x0 = np.array([0.5, 0.5, 0.5])
h = 0.01

# Estimar el Jacobiano usando el operador de orden O(h^4)
jacobiano_orden4 = jacobiano_central_orden4(funciones_5_68, x0, h)
print("Jacobiano (orden O(h^4)) en x = (0.5, 0.5, 0.5):")
print(jacobiano_orden4)
def jacobiano_central_orden2(func, x, h):
    """
    Estima el Jacobiano de una función vectorial usando el operador de derivada central de orden O(h^2).

    :param func: Función vectorial que toma un vector x y devuelve un vector.
    :param x: Punto en el que se calcula el Jacobiano (vector).
    :param h: Tamaño del paso.
    :return: Matriz Jacobiana estimada.
    """
    n = len(x)  # Dimensión del vector
    m = len(func(x))  # Dimensión del vector de salida
    J = np.zeros((m, n))

    for i in range(n):
        x_i_plus_h = np.array(x)
        x_i_minus_h = np.array(x)

        x_i_plus_h[i] += h
        x_i_minus_h[i] -= h

        J[:, i] = (func(x_i_plus_h) - func(x_i_minus_h)) / (2 * h)

    return J

# Estimar el Jacobiano usando el operador de orden O(h^2)
jacobiano_orden2 = jacobiano_central_orden2(funciones_5_68, x0, h)
print("\nJacobiano (orden O(h^2)) en x = (0.5, 0.5, 0.5):")
print(jacobiano_orden2)


Jacobiano (orden O(h^4)) en x = (0.5, 0.5, 0.5):
[[ -6.          -0.24740396  -0.24740396]
 [  0.37377753  -9.           0.32802064]
 [  1.16820117   1.16820117 -60.        ]]

Jacobiano (orden O(h^2)) en x = (0.5, 0.5, 0.5):
[[ 6.          0.24740293  0.24740293]
 [-0.37376854  9.         -0.32801836]
 [-1.16820604 -1.16820604 60.        ]]


In [18]:
# Comparar precisión para diferentes valores de h
h_values = [0.1, 0.05, 0.01, 0.005]
for h in h_values:
    jacobiano_orden4 = jacobiano_central_orden4(funciones_5_68, x0, h)
    jacobiano_orden2 = jacobiano_central_orden2(funciones_5_68, x0, h)

    error = np.linalg.norm(jacobiano_orden4 - jacobiano_orden2)
    print(f"Error entre Jacobiano de orden O(h^4) y O(h^2) para h={h}: {error:.6e}")


Error entre Jacobiano de orden O(h^4) y O(h^2) para h=0.1: 1.219852e+02
Error entre Jacobiano de orden O(h^4) y O(h^2) para h=0.05: 1.219852e+02
Error entre Jacobiano de orden O(h^4) y O(h^2) para h=0.01: 1.219852e+02
Error entre Jacobiano de orden O(h^4) y O(h^2) para h=0.005: 1.219852e+02
